version: '3'
services:
  web:
    build: 
      context: . 
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules # do not mapp our local node_modules/ directory TO node_modules/ inside our container
      - .:/app            # Map all files outside the container to APP directory inside the container  
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm","run" , "test"]